package com.uob.contextframework.support;

public enum ContextManagerServices {
	CTX_FRAMEWORK_LOCATION,
	CTX_FRAMEWORK_BATTERY,
	CTX_FRAMEWORK_SIGNALS,
	CTX_FRAMEWORK_WIFI,
	CTX_FRAMEWORK_EVENTS,
	CTX_FRAMEWORK_BLUETOOTH,
}
